### PR TITLE
Singledispatch entrypoints

### PR DESCRIPTION
**Pull request by deltamarnix**
I was playing with how we could set up functions in a modular fashion without having to add a function in the corresponding class. `cattrs` mentions the use of single dispatch functions for their `structure` and `unstructure` functions. We can do the same for functions like `plot()`, where the plot function should be seen as a module, and not as part of the class itself.

I have combined this functionality with the `entry_points` function to show that a user or plugin package could in theory also add functionality. For example, a user comes with a specific entry point for plotting a specific package, other than the default way that we normally do.

### CODE REVIEW

**Comment by deltamarnix** [comment]
Python 3.9 seems to fail, because the arguments for entry_points are wrong.

I wonder if we should still support this version of python: https://scientific-python.org/specs/spec-0000/

**Comment by wpbonelli** [comment]
> I wonder if we should still support this version of python: https://scientific-python.org/specs/spec-0000/

I figured we'd want to support 3.9 until EOL in Oct next year (https://devguide.python.org/versions/) but as a matter of personal preference I'd much rather take your source's advice and drop it earlier, if only so we can use 3.10 features like pattern matching

**Comment by deltamarnix** [comment]
> I figured we'd want to support 3.9 until EOL in Oct next year (https://devguide.python.org/versions/) but as a matter of personal preference I'd much rather take your source's advice and drop it earlier, if only so we can use 3.10 features like pattern matching

If we keep 3.9 supported, we might come in conflict with the latest versions of numpy and xarray. And then we are lacking behind. I think that's why these packages support only a small subset of python versions.

**Review by wpbonelli — APPROVED** [review]
I like it. Extensibility by design &mdash; reminds me of pytest, where most basic functionality is implemented in the same way external plugins are

**Comment by wpbonelli** [comment]
> If we keep 3.9 supported, we might come in conflict with the latest versions of numpy and xarray. And then we are lacking behind. I think that's why these packages support only a small subset of python versions.

True. I didn't realize numpy had already dropped 3.9. I say we just follow them?

**Review by wpbonelli — APPROVED** [review]

**Comment by wpbonelli** [comment]
Somewhat similar discussion: https://github.com/modflowpy/flopy/issues/1470

I don't know if @jlarsen-usgs still has plans for a flopy/modflowapi plugin architecture, more recently he has indicated modflowapi will stay separate from flopy.

But the entrypoints plugin approach seems applicable to the core flopy framework too, if we want the same "engine" to drive not only mf6 but other programs. This would of course expand the scope of this work &mdash; maybe wisest to design/build for mf6 initially, then consider extending it to other programs later.

**Pull request merged**
